In [2]:
import pandas as pd

l = [4, 8, 15, 16, 23, 42] 
pd.Series(l)

0     4
1     8
2    15
3    16
4    23
5    42
dtype: int64

In [3]:
import pandas as pd

# list containing 10 elements
numbers = [10, 20, 30, 40, 50, 60]

# converting list into pandas Series
series_data = pd.Series(numbers)

# printing the Series
print(series_data)

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64

In [10]:
import pandas as pd
dic = {
    "Name": ["Taruna"],
    "Age": ["27"],
}

df = pd.DataFrame(dic)
print(df)

     Name Age
0  Taruna  27

In [11]:
df.describe()

          Name Age
count        1   1
unique       1   1
top     Taruna  27
freq         1   1

In [12]:
df.head()

     Name Age
0  Taruna  27

In [ ]:
#Series, DataFrame, and Panel are mutable.

In [19]:
name = pd.Series(["Taruna", "Dinesh", "Papa"])
age = pd.Series(["23", "34", "50"])


df = pd.DataFrame({"Name": name, "Age": age})
    

print(df)

     Name Age
0  Taruna  23
1  Dinesh  34
2    Papa  50